[package]
name = "cli"
version = "0.1.0"
edition = "2021"
license = "The Unlicense"
description = "Cross-platform software helping to verify, prove and secure package compilation, building, fetching, and deployment. CLI interface."
homepage = "https://github.com/Meta-A/bpm"
repository = "https://github.com/Meta-A/bpm"
readme = "../../README.md"

[dev-dependencies]
cargo-tarpaulin.workspace = true

[dependencies]
core = { workspace = true }
clap = { version = "4.5.19", features = ["derive"] }
home = "0.5.9"
tempfile = "3.13.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "sync"] }
log.workspace = true
colored = "2.1.0"
dialoguer = { version = "0.11.0", features = ["history", "fuzzy-select"] }
indicatif = "0.17.8"
hex = "0.4.3"
url = "2.5.3"
strum = "0.26"
strum_macros = "0.26"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "bpm"
path = "src/main.rs"
