[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
cargo-tarpaulin.workspace = true

[dependencies]
core = { workspace = true }
clap = { version = "4.5.19", features = ["derive"] }
home = "0.5.9"
tempfile = "3.13.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
log.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
